BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "users" (
	"id"	INTEGER NOT NULL UNIQUE,
	"user"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "boxes" (
	"id"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT,
	"api"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "boxusers" (
	"id"	INTEGER NOT NULL UNIQUE,
	"box"	TEXT,
	"users"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
